services:
  - type: web
    name: flask-tailwind-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NODE_VERSION
        value: 18.17.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: GUNICORN_CMD_ARGS
        value: "--workers=4 --worker-class=gevent --timeout 120"
